### ISSUE TITLE
Can't see Wallet UI

### ISSUE THREAD

**Issue by madnight** [hcvst/cardano-daedalus-docker#1]
I'm able to execute the command `docker run -d --name=cardano -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=$DISPLAY hcvst/cardano-sl-with-daedalus-wallet` and docker ps shows:
```                                                                                                                                                                   CONTAINER ID        IMAGE                                   COMMAND                  CREATED             STATUS              PORTS               NAMES
5e863a436f21        hcvst/cardano-sl-with-daedalus-wallet   "/bin/sh -c 'cd daed…"   7 minutes ago       Up 7 minutes                            cranky_ramanujan
```

**Comment by hcvst** [comment]
What linux distro are you running on the docker host, please? Could you try to run `xhost +` on the host to allow the X11 connection from the docker container, please?

**Comment by madnight** [comment]
Arch Linux, meanwhile i managed to start the wallet without docker, but the wallet ui stucks at 100% sync

**Comment by hcvst** [comment]
I also just synced and it appeared to be stuck at 100% for quite a few mins.
Did you come right?

**Comment by madnight** [comment]
Still at 100%. I guess there is some problem with the wallet itself, other users face the same issue https://github.com/input-output-hk/daedalus/issues/603

**Comment by madnight** [comment]
Ah okay this helps: https://github.com/jessfraz/dockerfiles/issues/6#issuecomment-77789863

after executing:  
`xhost local:root`
i can now see the wallet of the docker container

**Comment by madnight** [comment]
By the way shouldn't there be a mount for the blockchain, so that one does not need to sync again on every docker start?

**Comment by h4ck3rm1k3** [comment]
We need a better error message if the start of electron fails.

**Comment by madnight** [comment]
However, your docker images finally works for me, great job :+1:
